import { defineStore } from 'pinia';
import actions from './_actions';
import getters from './_getters';

export const useSegmentManagerStore = defineStore('segmentManagerStore', {
    state: () => ({
        baseUrl: 'https://sm-standard-segments-838902823068.europe-west1.run.app',
        applicationType: '',
        tenantId: '',
        brandId: '3',
        token: '',
        brief: {},
        profiles: [],
        profile: {},
        selectedProfile: null,
        stateColors: {
            active: '#28a745',
            inactive: '#999999',
            pending: '#ffc107',
        },
        isFetchingSegments: false,
        activeTab: 'standard',
        segments: [],
        platform: 1,
        currentPage: 1,
        numberOfPages: null,
        segmentDatabaseModel: [],
        query: {
            page: 1,
            pageSize: 15,
            category: 1,
            sortField: null,
            sortDirection: 'desc',
            location: null,
            name: null,
            description: null,
            count: null,
            status: null,
            searchTerm: null,
            demographics: {
                region: '',
                market: '',
                language: '',
                channel: '',
            },
        },
        selectedFilters: {
            name: '',
            description: '',
            count: '',
            status: '',
        },
        settings: null,
        selectedSegment: null,
        selectedSegmentType: 'standard',
        audienceType: 'attr',
        market: null,
        fetchBriefsAbortController: null,
        fetchCalBriefsAbortController: null,
        apiError: null,
        appAlerts: [],
        appSettings: null,
    }),
    actions,
    getters,
});
